//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssesSection
    {
        public int SectionID { get; set; }
        public Nullable<int> SectionNr { get; set; }
        public string SectionName { get; set; }
        public Nullable<int> JobID { get; set; }
        public Nullable<int> ComapnyID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> AssesmentID { get; set; }
    }
}
