//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

    public partial class CandidatePersonalInfProfile
    {
        public int ID { get; set; }
        public string UserID { get; set; }
		[Required(ErrorMessage ="*")]
        public string Name { get; set; }
		[Required(ErrorMessage = "*")]
		public string Surname { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> RSACitizen { get; set; }
		[Required(ErrorMessage = "*")]
		public string CandidateIDNumber { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> Race { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> Gender { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> Disability { get; set; }
		[Required(ErrorMessage = "*")]
		public string CellphoneNumber { get; set; }
        public string TelephoneNumber { get; set; }
        public string EmailAddress { get; set; }
		[Required(ErrorMessage = "*")]
		public string StreetAddress { get; set; }
        public Nullable<int> TownID { get; set; }
		[Required(ErrorMessage = "*")]
		public string DriversLicense { get; set; }
        public string imgurl { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
