//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class CandidateQualification_
	{
		public int QualificationID { get; set; }
		public string UserID { get; set; }
		[Required(ErrorMessage ="*")]
        public Nullable<int> QualificationType { get; set; }
		[Required(ErrorMessage = "*")]
		public string Qualification { get; set; }
		[Required(ErrorMessage = "*")]
		public string Institution { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> YearCompleted { get; set; }
		[Required(ErrorMessage = "*")]
		public string MajorSubjects { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> ScoreAverage { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> YearStarted { get; set; }
    }
}
