//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

    public partial class CandidateWorkExperience
    {
        public int WorkExperienceID { get; set; }
        public string UserID { get; set; }
		[Required(ErrorMessage ="*")]
        public string JobTitle { get; set; }
		[Required(ErrorMessage = "*")]
		public string CompanyName { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> Sector { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<int> EmploymentBasis { get; set; }
		[Required(ErrorMessage = "*")]
		public string DescriptionOfDuties { get; set; }
		[Required(ErrorMessage = "*")]
		public Nullable<System.DateTime> JobStartDate { get; set; }
		public Nullable<System.DateTime> JobEndate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool CurrentEmployment { get; set; }
    }
}
