//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpowermentQuestion
    {
        public int EmpowermentQuestionID { get; set; }
        public int IndustryID { get; set; }
        public string Title { get; set; }
        public string EmpowermentQuestionName { get; set; }
        public string CapturedBy { get; set; }
        public System.DateTime CapturedDate { get; set; }
    }
}
