//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalInfoVW
    {
        public string Town { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string CandidateIDNumber { get; set; }
        public string Race { get; set; }
        public string Gender { get; set; }
        public string DriversLicense { get; set; }
        public string StreetAddress { get; set; }
        public string EmailAddress { get; set; }
        public string TelephoneNumber { get; set; }
        public string CellphoneNumber { get; set; }
        public string Disability { get; set; }
        public string UserID { get; set; }
        public int ID { get; set; }
        public string imgurl { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RSA_Citizen { get; set; }
        public int TownID { get; set; }
        public Nullable<int> RegionID { get; set; }
        public string ProvinceName { get; set; }
        public string Region { get; set; }
    }
}
