//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageDocumentLibrary
    {
        public int RecordID { get; set; }
        public string UserID { get; set; }
        public int UserTypeID { get; set; }
        public int DocumentTypeID { get; set; }
        public string DocumentURL { get; set; }
        public string Comments { get; set; }
        public string DocName { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
