//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageJobs
    {
        public int JobID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string JobCode { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public Nullable<System.DateTime> AdvertStart { get; set; }
        public Nullable<System.DateTime> AdvertEnd { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<System.DateTime> CapturedBy { get; set; }
        public Nullable<System.DateTime> CapturedDate { get; set; }
        public Nullable<System.DateTime> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UserID { get; set; }
    }
}
