//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblJobs_020520172000_backup
    {
        public int JobID { get; set; }
        public string JobCode { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public string JobDescription { get; set; }
        public string CandidateRequirements { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> EmploymentBasisID { get; set; }
        public Nullable<int> NumberOfPositions { get; set; }
        public Nullable<System.DateTime> AdvertDate { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public string CapturedBy { get; set; }
        public Nullable<System.DateTime> CapturedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<int> JobLevelID { get; set; }
        public Nullable<int> RemunerationID { get; set; }
    }
}
