//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwApplicantsPerJob
    {
        public int JobAppID { get; set; }
        public Nullable<int> JobID { get; set; }
        public string UserID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string CandidateIDNumber { get; set; }
        public string Gender { get; set; }
        public string Race { get; set; }
        public string CellphoneNumber { get; set; }
    }
}
