//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCompanyDetailed
    {
        public int CompanyID { get; set; }
        public string CreatedBy { get; set; }
        public string MobileNumber { get; set; }
        public string CompanyName { get; set; }
        public string CompanyRegistrationNumber { get; set; }
        public string CompanyTelephoneNumber { get; set; }
        public string CompanyEmail { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanySize { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> YearsInBusiness { get; set; }
        public Nullable<int> BusinessSector { get; set; }
        public string Industry { get; set; }
        public string BEELevelName { get; set; }
        public string Town { get; set; }
        public string Region { get; set; }
        public string ProvinceName { get; set; }
        public string imgUrl { get; set; }
    }
}
