//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWJobType
    {
        public string JobTypeName { get; set; }
        public Nullable<int> CountJobs { get; set; }
        public int JobTypeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
