//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwJobs
    {
        public int ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public string Region { get; set; }
        public string Town { get; set; }
        public int JobID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public string SmallDesc { get; set; }
        public string JobDescription { get; set; }
        public Nullable<int> JobLevelID { get; set; }
        public string RemunerationTo { get; set; }
        public string RemunerationFrom { get; set; }
        public string CandidateRequirements { get; set; }
        public Nullable<int> TownID { get; set; }
        public Nullable<int> EmploymentBasisID { get; set; }
        public Nullable<int> NumberOfPositions { get; set; }
        public Nullable<System.DateTime> AdvertDateSartDate { get; set; }
        public Nullable<int> NumberOfMonths { get; set; }
        public string CapturedBy { get; set; }
        public Nullable<System.DateTime> CapturedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public string JobType { get; set; }
        public Nullable<int> JobTypeID { get; set; }
        public string imgUrl { get; set; }
        public string CustomRemuneration { get; set; }
        public string RemunerationName { get; set; }
        public Nullable<int> RemunerationType { get; set; }
        public Nullable<int> RateType { get; set; }
        public string RateName { get; set; }
    }
}
