//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwLanguageCompetency
    {
        public string Language { get; set; }
        public int CandidateLanguageID { get; set; }
        public string UserID { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Write { get; set; }
        public string Speak { get; set; }
        public string Read { get; set; }
        public int LanguageID { get; set; }
    }
}
