//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwQualificationView
    {
        public Nullable<int> QualificationType { get; set; }
        public string HighestQualification { get; set; }
        public string UserID { get; set; }
        public string Qualification { get; set; }
        public string Institution { get; set; }
        public Nullable<int> YearCompleted { get; set; }
        public string MajorSubjects { get; set; }
        public Nullable<int> ScoreAverage { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> YearStarted { get; set; }
        public int QualificationID { get; set; }
    }
}
