//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSkills
    {
        public string CompetencyName { get; set; }
        public int RecordID { get; set; }
        public string UserID { get; set; }
        public string Skill { get; set; }
        public Nullable<int> Competency { get; set; }
        public Nullable<int> Experience { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
