//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQRecruitmentTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingExperienceVW
    {
        public string UserID { get; set; }
        public string JobTitle { get; set; }
        public string Sector { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> EmploymentBasis { get; set; }
        public Nullable<System.DateTime> JobStartDate { get; set; }
        public string DescriptionOfDuties { get; set; }
        public Nullable<System.DateTime> JobEndate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string Industry { get; set; }
    }
}
